# Generated by Django 5.1.4 on 2026-02-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('issue_type', models.CharField(max_length=200)),
                ('risk_level', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('low', 'Low')], max_length=20)),
                ('action', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_health', models.FloatField(default=96.0)),
                ('active_critical_faults', models.IntegerField(default=5)),
                ('assets_at_risk', models.IntegerField(default=18)),
                ('downtime_risk_avoided', models.DecimalField(decimal_places=2, default=1200000, max_digits=12)),
                ('health_change', models.IntegerField(default=2)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'get_latest_by': 'recorded_at',
            },
        ),
        migrations.CreateModel(
            name='SustainabilityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_emissions_avoided', models.FloatField(default=620.0)),
                ('asset_life_extended', models.FloatField(default=32.0)),
                ('energy_efficiency_gain', models.FloatField(default=14.0)),
                ('compliance_status', models.FloatField(default=100.0)),
                ('preventive_replacements_count', models.IntegerField(default=4)),
                ('cables_avoided_replacement', models.IntegerField(default=64)),
                ('carbon_saved_kg', models.FloatField(default=620.0)),
                ('last_report_generated', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'get_latest_by': 'recorded_at',
            },
        ),
    ]
